version: 2.1


jobs:
  save_hello_world_output:
    docker:
      - image: cimg/node:17.2.0
        auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
  
    steps:
      - checkout
      - run: echo "text to output here" > output.txt
  
  # print_output_file:

workflows:
  build_and_run:
    jobs:
      - save_hello_world_output

